title: Epilepsy Gene Variant Analysis
description: Comprehensive variant analysis for SCN2A, EEF1A2, KCNQ2, SYNGAP1, CDKL5
theme: jekyll-theme-cayman
baseurl: "/Epilepsy_phenotype"
url: "https://ykshim2013.github.io"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
